### ISSUE TITLE
`flutter pub get` does not work.

### ISSUE THREAD

**Issue by finorix079** [NoaTubic/photopulse#2]
The error message I received:

> Resolving dependencies... (3.5s)
> Because http_client_helper >=3.0.0 depends on http ^1.0.0 and gallery_saver >=2.1.1 depends on http ^0.13.3, http_client_helper >=3.0.0 is incompatible with gallery_saver >=2.1.1.
> So, because photopulse depends on both gallery_saver ^2.3.2 and http_client_helper ^3.0.0, version solving failed.

**Comment by NoaTubic** [comment]
@terryjiang2020 You need to update the dependencies.
